spring:
  datasource:
    driver-class-name:org.postgresql.Driver
    url:jdbc:postgresql://localhost:5434/backend
    username:serious
    password:123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto:create-drop
